data:
  start_date: '2024-01-01'
  end_date: '2025-01-01'
  #currencies: ['usd']

data_prep:
  seq_len:
    10

model:
  path_to_last_model:
    './models/latest_rnn.pth'
  name:
    'rnn_model'
  input_size:
    1
  hidden_layer_size:
    128
  num_layers:
    1
  output_size:
    1

train:
  lr:
    0.001
  num_epoch:
    3000




